import fs from 'fs';
import os from 'os';
import path from 'path';
import { ReportCleanup } from './reportCleanup';
import { SetupConstants } from '../support/constants/SetupConstants';
const report = require('multiple-cucumber-html-reporter');

export class ReportGenerator {
    public static generate(): void {
        const timeStamp = ReportGenerator.getTimestamp();
        const baseReportDir = 'reports/html';
        const reportPath = path.join(baseReportDir, timeStamp);

        // Ensure the report output directory exists
        fs.mkdirSync(reportPath, { recursive: true });

        report.generate({
            jsonDir: 'reports', // Your cucumber_report.json should be here
            reportPath,
            reportName: 'Playwright Test Execution Report',
            pageTitle: 'Test Report - Playwright + Cucumber',
            displayDuration: true,
            displayReportTime: true,
            reportSuiteAsScenarios: true,
            openReportInBrowser: process.env.CI ? false : true,
            classificationTags: ['@smoke', '@regression', '@login'],
            metadata: {
                browser: {
                    name: 'chrome',
                    version: '114',
                },
                device: os.hostname(),
                platform: {
                    name: process.platform,
                    version: process.version,
                },
            },
            customData: {
                title: 'Execution Info',
                data: [
                    { label: 'Project', value: 'Playwright Cucumber Framework' },
                    { label: 'Executed By', value: process.env.USER || 'Automation Team' },
                    { label: 'Branch', value: process.env.GIT_BRANCH || 'main' },
                    { label: 'Release', value: 'v1.0.0' },
                    { label: 'Environment', value: process.env.ENV || 'QA' },
                    { label: 'Execution Start Time', value: new Date().toLocaleString() },
                    { label: 'Execution End Time', value: new Date().toLocaleString() },
                ],
            },
            pageFooter:
                "<div style='text-align:center;font-size:12px;padding:10px;'>Report generated by the Automation Team using Playwright & CucumberJS</div>",
        });
    }

    private static getTimestamp(): string {
        const now = new Date();
        return now.toISOString().replace(/[:.]/g, '-').replace('T', '_').slice(0, 19);
    }
}

ReportGenerator.generate();
ReportCleanup.cleanOldReports(SetupConstants.FIVE);